from youtube_transcript_api import YouTubeTranscriptApi
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_huggingface import HuggingFaceEmbeddings
from langchain_community.vectorstores import FAISS
from urllib.parse import urlparse, parse_qs
import os
import subprocess

def return_video_id(link: str) -> str:
    parsed_url = urlparse(link)

    # Case 1: Standard YouTube link
    if parsed_url.hostname in ["www.youtube.com", "youtube.com"]:
        query = parse_qs(parsed_url.query)
        return query.get("v", [None])[0]

    # Case 2: Shortened youtu.be link
    if parsed_url.hostname == "youtu.be":
        return parsed_url.path.lstrip("/")

    return None



def generate_vector_store(video_link):
    video_id = return_video_id(video_link)
    try:
        ytt_api = YouTubeTranscriptApi()
        transcript_list = ytt_api.fetch(video_id)
        transcript_text = " ".join(snippet.text for snippet in transcript_list.snippets)
    except Exception as e:
        print("Transcript API failed:",e)

        try:
            subprocess.run([
                "yt-dlp",
                "--write-auto-sub",
                "--skip-download",
                f"{video_link}"
            ], check=True)
            # Look for any .vtt file generated
            vtt_file = None
            for file in os.listdir("."):
                if file.startswith(video_id) and file.endswith(".vtt"):
                    vtt_file = file
                    break

            if vtt_file:
                transcript_lines = []
                with open(vtt_file, "r", encoding="utf-8") as f:
                    for line in f:
                        # Skip timestamps and metadata
                        if not line.strip() or "-->" in line:
                            continue
                        transcript_lines.append(line.strip())
                transcript_text = " ".join(transcript_lines)
            else:
                print("No transcript file generated by yt-dlp")
                return "No Transcript on video"
        except Exception as e2:
            print("yt-dlp fallback failed:", e2)
            return "No Transcript on video"


    
    # Step 1b Indexing (Text Splitting)
    splitter = RecursiveCharacterTextSplitter()
    chunks = splitter.create_documents([transcript_text])

    # Step 1c, 1d Indexing (Embedding and storing in Vectorstore)
    embeddings = HuggingFaceEmbeddings(model_name="sentence-transformers/all-mpnet-base-v2")
    vector_store = FAISS.from_documents(chunks,embeddings)

    return vector_store
